[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

[[scheduled.functions]]
  name = "fetchEmails"
  cron = "0 * * * *" # Runs every hour
